"""attendance module and advanced door flags

Revision ID: 995243b73005
Revises: fad72c79e7db
Create Date: 2026-07-10 11:56:47.533584

"""
from alembic import op
import sqlalchemy as sa


revision = '995243b73005'
down_revision = 'fad72c79e7db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('late_tolerance_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_tolerance_minutes', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_organization_id'), ['organization_id'], unique=False)

    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardholder_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LEAVE', 'BUSINESS_TRIP', name='leavetype'), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardholder_id'], ['cardholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaves_cardholder_id'), ['cardholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaves_organization_id'), ['organization_id'], unique=False)

    op.create_table('manual_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardholder_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('IN', 'OUT', name='signkind'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardholder_id'], ['cardholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_signs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_signs_cardholder_id'), ['cardholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_signs_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('cardholders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_cardholders_shift_id', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('interlock_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('doors', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('first_card_open', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('multi_card_count', sa.Integer(), nullable=False, server_default='1')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doors', schema=None) as batch_op:
        batch_op.drop_column('multi_card_count')
        batch_op.drop_column('first_card_open')

    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_column('interlock_enabled')

    with op.batch_alter_table('cardholders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cardholders_shift_id', type_='foreignkey')
        batch_op.drop_column('shift_id')

    with op.batch_alter_table('manual_signs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_signs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_manual_signs_cardholder_id'))

    op.drop_table('manual_signs')
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaves_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leaves_cardholder_id'))

    op.drop_table('leaves')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_organization_id'))

    op.drop_table('shifts')
    # ### end Alembic commands ###
